### ISSUE TITLE
Deep sorting affects stage order for Query Pipelines

### ISSUE THREAD

**Issue by gwynnebaer** [andrewshumway/Fusion_getPut#4]
Issue: When using new deep sorting routine, the query pipeline stage order is not preserved.

Before I submit a PR to undo the entire change, I will review what object types are impacted by sort order and will revert just those objects.

**Comment by gwynnebaer** [comment]
Spark jobs are also impacted. Therefore, it is better to revert these changes as too aggressive. Apologies for not getting this better. I will review further before I submit a new patch.

**Comment by andrewshumway** [comment]
Thank you for the heads up. Obviously, pipeline stages are in an array so
any sorting there will break the order contract. Note that there was
already a sort in the json.dumps. I doubt it impacts you but want to call
attention to it just in case.

**Comment by andrewshumway** [comment]
@gwynnebaer 
how confident are you that the new deep sorting changes pipeline stage order?  I've run several tests and can not find a case where the order changed.  Do you by chance have a sample pipeline I can test on?

**Comment by andrewshumway** [comment]
I verified that the deep sort does sort the arrays so I'm rolling that back.  I also verified that the dumps(sort_keys=True) sorts nested keys (deep) so that remains.
